question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Goldfish only have a memory span of three seconds.", "answer": "False"},
    {"text": "A sneeze travels faster than a cheetah.", "answer": "False"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "Humans can distinguish over a million different colors.", "answer": "True"},
    {"text": "Ostriches can run faster than horses.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The longest hiccuping spree lasted over 60 years.", "answer": "True"},
    {"text": "Birds are descendants of dinosaurs.", "answer": "True"},
    {"text": "Carrots improve your vision.", "answer": "False"},
    {"text": "Venus spins clockwise.", "answer": "True"},
    {"text": "A jellyfish is 95% water.", "answer": "True"},
    {"text": "A rhinoceros' horn is made of hair.", "answer": "True"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "Cows can sleep standing up.", "answer": "True"},
    {"text": "Humans lose more hair in the summer than in the winter.", "answer": "True"},
    {"text": "Koalas are bears.", "answer": "False"},
    {"text": "A crocodile cannot stick out its tongue.", "answer": "True"},
    {"text": "The human body contains enough iron to make a 3-inch nail.", "answer": "True"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "It takes 8 minutes for light from the Sun to reach Earth.", "answer": "True"},
    {"text": "Some turtles can breathe through their butts.", "answer": "True"},
    {"text": "The heart of a blue whale is the size of a car.", "answer": "True"},
    {"text": "Humans are the only animals that blush.", "answer": "True"},
    {"text": "The Empire State Building has its own zip code.", "answer": "True"},
    {"text": "Diamonds are made of carbon.", "answer": "True"},
    {"text": "Octopuses have blue blood.", "answer": "True"},
    {"text": "Cucumbers are 95% water.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "Snakes can blink.", "answer": "False"},
    {"text": "Hot water freezes faster than cold water.", "answer": "True"},
    {"text": "Humans have five senses.", "answer": "False"},
    {"text": "There are more chickens than people on Earth.", "answer": "True"},
    {"text": "A giraffe's tongue is blue.", "answer": "True"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "Polar bears have black skin.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "Sea otters hold hands while sleeping.", "answer": "True"},
    {"text": "Horses can vomit.", "answer": "False"},
    {"text": "The Earth is closer to the sun in winter than in summer.", "answer": "True"},
    {"text": "Humans and giraffes have the same number of neck vertebrae.", "answer": "True"},
    {"text": "The Statue of Liberty was originally intended for Egypt.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Pineapples grow on trees.", "answer": "False"},
    {"text": "Elephants are the only animals that can't jump.", "answer": "True"},
    {"text": "Humans can breathe in space without a spacesuit.", "answer": "False"},
    {"text": "An adult human has 206 bones.", "answer": "True"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"text": "Humans can survive without a gallbladder.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "The Sun is a star.", "answer": "True"},
    {"text": "Cheetahs can retract their claws.", "answer": "False"},
    {"text": "Some cats are allergic to humans.", "answer": "True"},
    {"text": "A banana is a berry.", "answer": "True"},
    {"text": "There are 24 hours in a day.", "answer": "False"},
    {"text": "The average human body temperature is 37°C (98.6°F).", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "All clownfish are born male.", "answer": "True"},
    {"text": "The longest river in the world is the Nile.", "answer": "False"},
    {"text": "Cats can't taste sweet things.", "answer": "True"},
    {"text": "The national bird of the United States is the Bald Eagle.", "answer": "True"},
    {"text": "A bee can sting only once before it dies.", "answer": "True"},
    {"text": "The fastest land animal is the peregrine falcon.", "answer": "False"},
    {"text": "Lightning is hotter than the surface of the sun.", "answer": "True"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "Kangaroos can't walk backwards.", "answer": "True"},
    {"text": "Slugs have four noses.", "answer": "True"},
    {"text": "Peanuts are nuts.", "answer": "False"},
    {"text": "You lose most of your body heat through your head.", "answer": "False"},
    {"text": "Jupiter is the largest planet in the solar system.", "answer": "True"},
    {"text": "Frogs drink water through their skin.", "answer": "True"}
]
